CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Modules" (
    "ModuleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ModuleTitle" text NOT NULL,
    "ModuleDescription" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Modules" PRIMARY KEY ("ModuleId")
);

CREATE TABLE "User" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserExternalId" text NOT NULL,
    "UserFirstName" text NOT NULL,
    "UserLastName" text NOT NULL,
    "UserEmail" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId")
);

CREATE TABLE "UserProgressRecords" (
    "UserProgressId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ModuleId" integer NOT NULL,
    "Progress" integer NOT NULL,
    "LastAccessed" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserProgressRecords" PRIMARY KEY ("UserProgressId"),
    CONSTRAINT "FK_UserProgressRecords_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserProgressRecords_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_User_UserEmail" ON "User" ("UserEmail");

CREATE UNIQUE INDEX "IX_User_UserExternalId" ON "User" ("UserExternalId");

CREATE INDEX "IX_UserProgressRecords_ModuleId" ON "UserProgressRecords" ("ModuleId");

CREATE INDEX "IX_UserProgressRecords_UserId" ON "UserProgressRecords" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250618114441_InitialCreate', '9.0.6');

ALTER TABLE "User" ADD "OrganisationId" integer;

CREATE TABLE "Organisations" (
    "OrganisationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationName" text NOT NULL,
    "Domain" text NOT NULL,
    CONSTRAINT "PK_Organisations" PRIMARY KEY ("OrganisationId")
);

CREATE TABLE "Packages" (
    "PackageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PackageName" text NOT NULL,
    "PackageDescription" text NOT NULL,
    CONSTRAINT "PK_Packages" PRIMARY KEY ("PackageId")
);

CREATE TABLE "ModulePackages" (
    "ModuleId" integer NOT NULL,
    "PackageId" integer NOT NULL,
    CONSTRAINT "PK_ModulePackages" PRIMARY KEY ("ModuleId", "PackageId"),
    CONSTRAINT "FK_ModulePackages_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") ON DELETE CASCADE,
    CONSTRAINT "FK_ModulePackages_Packages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "Packages" ("PackageId") ON DELETE CASCADE
);

CREATE TABLE "OrganisationPackages" (
    "OrganisationId" integer NOT NULL,
    "PackageId" integer NOT NULL,
    CONSTRAINT "PK_OrganisationPackages" PRIMARY KEY ("OrganisationId", "PackageId"),
    CONSTRAINT "FK_OrganisationPackages_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("OrganisationId") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationPackages_Packages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "Packages" ("PackageId") ON DELETE CASCADE
);

CREATE INDEX "IX_User_OrganisationId" ON "User" ("OrganisationId");

CREATE INDEX "IX_ModulePackages_PackageId" ON "ModulePackages" ("PackageId");

CREATE INDEX "IX_OrganisationPackages_PackageId" ON "OrganisationPackages" ("PackageId");

CREATE UNIQUE INDEX "IX_Organisations_Domain" ON "Organisations" ("Domain");

ALTER TABLE "User" ADD CONSTRAINT "FK_User_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("OrganisationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250620103855_AddLicensingAndOrganisationStructure', '9.0.6');

ALTER TABLE "Modules" ADD "CoverImageUrl" text NOT NULL DEFAULT '';

ALTER TABLE "Modules" ADD "Duration" text NOT NULL DEFAULT '';

ALTER TABLE "Modules" ADD "LastUpdated" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250710141548_AddModuleMetadata', '9.0.6');

ALTER TABLE "Modules" ADD "Slug" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250711220057_AddSlugToModules', '9.0.6');

CREATE TABLE "BlogPosts" (
    "BlogPostId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Slug" character varying(200) NOT NULL,
    "Excerpt" text,
    "Content" text NOT NULL,
    "CoverImageUrl" text,
    "Author" text,
    "Tags" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "PublishedAt" timestamp with time zone,
    CONSTRAINT "PK_BlogPosts" PRIMARY KEY ("BlogPostId")
);

CREATE UNIQUE INDEX "IX_BlogPosts_Slug" ON "BlogPosts" ("Slug");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250831184531_AddBlogPosts', '9.0.6');

ALTER TABLE "UserProgressRecords" ADD "CompletedAt" timestamp with time zone;

ALTER TABLE "Modules" ADD "BadgeImageUrl" text;

ALTER TABLE "Modules" ADD "CertificateTemplateUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251010104859_AddBadgeFieldsAndCompletedAt', '9.0.6');

ALTER TABLE "Packages" ADD "ColorHex" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251010121349_AddPackageColor', '9.0.6');

CREATE TABLE "Feedback" (
    "FeedbackId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ModuleId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Rating" smallint NOT NULL,
    "Comment" character varying(2000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Feedback" PRIMARY KEY ("FeedbackId"),
    CONSTRAINT "CK_Feedback_Rating" CHECK ("Rating" >= 1 AND "Rating" <= 5),
    CONSTRAINT "FK_Feedback_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") ON DELETE CASCADE,
    CONSTRAINT "FK_Feedback_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_Feedback_ModuleId" ON "Feedback" ("ModuleId");

CREATE INDEX "IX_Feedback_UserId" ON "Feedback" ("UserId");

CREATE UNIQUE INDEX "IX_Feedback_UserId_ModuleId" ON "Feedback" ("UserId", "ModuleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251222213725_AddModuleFeedback', '9.0.6');

COMMIT;

